### ISSUE TITLE
can't make bt to work

### ISSUE THREAD

**Issue by jlcurty** [Seeed-Studio/Lua_for_RePhone#11]
hi,

I'm trying to use bt with my iphone, but the iphone doesn't detect rephone ...
I see in the source code that some part of the code is commented like the read function,
anyone succeeded with bluetooth ? can you share a lua code sample ?
thanks
jl

**Comment by KillingJacky** [comment]
Hi @jlcurty , do you mean enable the bluetooth via lua scripts? or any other way that can make your iphone detect the RePhone?

**Comment by KillingJacky** [comment]
Will close this issue, please open a new issue if you have further questions.
