### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by msva** [Seeed-Studio/Lua_for_RePhone#2]
Hi there!
Unfortunately, project (as many RePhone things, tho) lacks documentation very much.

It'd be nice to have some usage examples in README. And, filling wiki with some API-descrbing articles would be nice too.

And, I'd like to try to contribute that, if I could fix #1 somehow :(

**Comment by xiongyihui** [comment]
Document will be added to https://github.com/Seeed-Studio/Lua_for_RePhone/wiki
