### ISSUE TITLE
No lua command prompt via putty

### ISSUE THREAD

**Issue by orsonfrut** [Seeed-Studio/Lua_for_RePhone#4]
Impossible to connect to Rephone via Putty, even after upgrading the firmware. 

I use the COM port specified in device manager (Debug Port) and the following parameters in PUTTY:

COM16
9600 (Speed)
8 (Data bits)
1 (Stop Bits)
None (Parity)
None (flow Control)

and I checked Implicit CR in every LF.

Thanks for your help!!

**Comment by xiongyihui** [comment]
Hi, the lua shell uses the USB Modem Port.

**Comment by pirj** [comment]
Same here. 

`minicom -D /dev/cu.usbmodem1411` opens MT2502 modem interface:

```
AT+
ERROR
```

While `minicom -D /dev/cu.usbmodem1413` doesn't echo.

Tried flashing both W15.19-p2-uart bundled with RePhone Arduino IDE's FlashTool.exe and W15.29 from https://github.com/WayenWeng/RePhone_SDK_Bin_Update

**Comment by pirj** [comment]
PS Using 115200 8N1.

**Comment by WayenWeng** [comment]
The firmware of version 15.19 is for Arduino IDE, it enable the serial output.
The firmware of version 15.29 is for Eclipse IDE, it enable the monitor output.
If use the firmware of version 15.29 to Rehone, the Arduino serial port is off, and the Eclipse monitor port is on.
So it need update the firmware of version 15.19, and USB Modem Port.
Please try it again.

**Comment by pirj** [comment]
Worked perfectly fine with 15.19. For the curious run as `sudo cu -l /dev/cu.usbmodem1411` or `screen /dev/tty.usbmodem1411`.

@orsonfrut Ports under windows are swapped, so on Debug port expect `ATE1` to work, while `print("halo")` will work on Modem port.

**Comment by siddharthtaunk** [comment]
I have lua 15.19 version
As 'pirj' mentioned ATE1 works on debug port
but print("hello") is nopt working on the Modem port
My settings in Putty are as follows
115200 8N1
Implicit CR in Every LF is checked

Please help
