### ISSUE TITLE
Cannot get init.lua to work

### ISSUE THREAD

**Issue by pirj** [Seeed-Studio/Lua_for_RePhone#8]
Saving `init.lua` with the following:

```
gpio.mode(17, gpio.OUTPUT)

function repeat_function()
  gpio.write(17, 1)
end

function repeat_function2()
  gpio.write(17, 0)
end

timer.create(2000, repeat_function)
timer.create(3000, repeat_function2)
```

Where gpio 17 is a red led on board.

Works (slowly flashes red) with lua.vxp that comes and/or is compiled with https://github.com/loboris/RePhone_on_Linux, but not the one from this project.

No log files, unable to connect to debug port (neither under Windows neither under OSX).

**Comment by pirj** [comment]
Got connected to debug port, however:

```
$ sudo cu -l /dev/cu.usbmodem1411
Connected.
print('dfsfd')
              dfsfd
                   > gpio.write(17,0)
                                     > gpio.mode(17,gpio.OUTPUT)
                                                                > gpio.write(17,0)
                                                                                  > gpio.write(12,1)
```

No LED change (green is on).

**Comment by WayenWeng** [comment]
Hi, add the pin number of RGB LED, and it is ok, pls try again.

https://github.com/WayenWeng/Lua_for_RePhone/blob/master/linkit/include/vmboard.h
Start line 103 ...
https://github.com/WayenWeng/Lua_for_RePhone/blob/master/linkit/lib/LINKIT10/src/gccmain.c
Start line 419 ...
